steps:
  - name: build
    image: "mcr.microsoft.com/dotnet/sdk:8.0"
    commands:
      - dotnet build
  - name: notify
    image: appleboy/drone-discord
    settings:
      webhook_id: "1153411637798256812"
      webhook_token: uOYeNBqMficnlewVy3hFR4iwYPsdPNhgUxFOxIaEXhd35KNcHx7gJW_d9PwLzWOOi5YK
