name: dotnet package

on: [ push ]

jobs:
  build:
    runs-on: windows-latest
    steps:
#      - uses: egor-tensin/setup-mingw@v2
#        with:
#          platform: x64
#        if: runner.os == 'Windows'
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: make
      - name: Capture Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: Voxel/bin/Release/net7.0
